### ISSUE TITLE
MemoryError: Cannot allocate write+execute memory for ffi.callback()

### ISSUE THREAD

**Issue by askaliuk** [pyca/pyopenssl#873]
For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

Found originally here: https://github.com/scrapy/scrapy/issues/4117
Seems like pyOpenSSL issue, that's why creating it here.

Any advice or workaround is appreciated. 

Traceback:
```
.... skipped as non-relevant ...
 File "/home/scrapy/env/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1709, in _makeContext
    ctx.set_verify(verifyFlags, _verifyCallback)
  File "/home/scrapy/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1103, in set_verify
    self._verify_helper = _VerifyHelper(callback)
```

OS:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
```

**Comment by steve-estes** [comment]
FWIW, I get the same message, on Ubuntu 18.04.3.  It actually results in the same stack trace even when I go to execute other things (like install unrelated packages via pip).  Uninstalling pyOpenSSL (after the scrapy install) allowed other installations to proceed, showing that it was pyOpenSSL related, but of course scrapy and other dependants can't fully function without it.

Andrii's first link above suggests some workarounds, but not for Ubuntu.

**Comment by tiran** [comment]
pyOpenSSL is not compatible with systems that prevent writeable and executable memory pages. You either have to disable the security feature, use another TLS library like the builtin ssl module, or redesign+rewrite pyOpenSSL's callback system.

**Comment by steve-estes** [comment]
Yeah, seems like there's a ready way to fix the code by changing to new-style ["Extern Python"](https://cffi.readthedocs.io/en/latest/using.html#id4) callbacks in CFFI.  Here's another project that ran into the same issue and fixed it that way, with a real fast turnaround:

Issue: https://github.com/FSX/misaka/issues/72
Commit: https://github.com/FSX/misaka/commit/321357b192235438aaa94061626a1fd7c3b3c67b#diff-cd1259298a2efe394f2d1bbea8b0d39e

I'm not familiar enough with the pyOpenSSL codebase to risk giving it a try, but otherwise it seems fairly straightforward - and would add some performance too, according to CFFI.

**Comment by jeromepin** [comment]
I know this is almost a year later, but I too have the issue using my M1 Silicon mac. [I first encountered it using Azure's CLI](https://github.com/Azure/azure-cli/issues/16907) and then with home-made softwares, while it was working great on Intel platforms (both darwin and linux).

Reading the answers above, does it mean every library using openssl has to made that kind of changes ?

**Comment by tiran** [comment]
tl;dr it's a problem in pyOpenSSL. OpenSSL is fine.

I see how my comment can be understand the wrong way. I was referring to another **Python** TLS library such as ssl module from Python's standard library. OpenSSL does not require executable+writable memory. The problem only effects pyOpenSSL.

It's an implementation artifact of pyOpenSSL's glue code that wraps OpenSSL's C-API and makes it available for Python. pyOpenSSL uses CFFI, which is a Python interface to libffi. libffi (library for foreign function interface) uses dynamic code creation for dynamic callbacks. Every time the code passes a Python method to OpenSSL, it has to wrap the Python method into machine code, so it looks like a C function to the C-API of OpenSSL. It **writes** dynamic code to an **executable** memory page. CFFI calls this [old style callbacks](https://cffi.readthedocs.io/en/latest/using.html#callbacks).

There are ways to work around the problem, but it's complicated and lots of work. Nobody has contributed a solution yet.

**Comment by thomasaarholt** [comment]
This issue seems to be blocking [snowflake-python-connector](https://github.com/snowflakedb/snowflake-connector-python) and hence [dbt](https://github.com/dbt-labs/dbt), as well as some other packages (see mentions above),  from running on M1 (arm64) Macs.

Is there anyone who could take a look at this?

**Comment by tiran** [comment]
It would take a serious effort and redesign to address the issue. Somebody would have to replace all existing callbacks in PyCA cryptography and pyOpenSSL with a different design. It's a non-trivial effort, because the implementation must be thread-safe and multi subinterpreter-safe. The effort could easily take two weeks or more even for an expert.

At work we had similar issues with SELinux enforcement of read-only executable mmap pages. We followed a different approach and replaced pyOpenSSL with Python's ssl module.

**Comment by thomasaarholt** [comment]
@tiran Thanks for the comment! I'll suggest dbt/snowflake-connector do the same thing you folks did.

**Comment by keyserwood** [comment]
Still having this issue on apple m1 2020, when launching API calls via asyncio [python 3.8.12 & natively installed - no rosetta here]. Hope that folks buying new MacBook Pro with M1 chip will push to fix this kind of issues 🤞

**Comment by fgiroud** [comment]
Same issue with the new macbook pros M1 (no rosetta)

**Comment by xros** [comment]
Same problem on M1 MacBook Pro. It's going to be year 2022 and Apple Silicon is still not supported.

**Comment by reaperhulk** [comment]
That attitude is extremely unproductive. As always, please try to remember that these are open source projects and someone has to actually do the work to fully understand the problem and implement a fix. Posts like yours are at best an irritant and quite frequently actively harmful.

**Comment by alex** [comment]
And not for nothing, but our test suite runs without segfaulting on an M1, so either our coverage is lousy (quite possible!) or there's slightly more involved in reproducing this than just using an M1.

**Comment by n8henrie** [comment]
FWIW, I've been following this issue for about a year after (like the OP) encountering it on Scrapy on my M1 MBP ([0], [1]). I've come back to it every few months to see if it was still crashing (and it has been).

After seeing @alex's comment I wanted to see if I could contribute to the test suite, and lo and behold the crash is gone.

- M1 Macbook Pro
- MacOS 12.0.1
- Python 3.10.0
- Scrapy==2.5.1

My test case has always been:

```console
$ scrapy shell 'http://httpforever.com/' # <- succeeds
$ scrapy shell 'https://n8henrie.com' # <- crashes with `Cannot allocate write+execute memory for ffi.callback()`
```

For me, both seem to now work without error on `http` or `https` sites, so perhaps some of the others following this thread might recheck to see if it is still an issue for them or not.

[0]: https://www.reddit.com/r/scrapy/comments/mn27t7/m1_mac_cffi_error/
[1]: https://stackoverflow.com/a/68061379/1588795

**Comment by xros** [comment]
> 

I have tested the latest verion of pyopenssl with Python 3.10.0 and 3.9.9 on M1 MacBook Pro, it turns out (probably) a problem of the Python Interpreter on M1. The Python interpreter 3.10 (might) change the ways to access(write) memory on M1 chips.

It works on both Python 3.10.0 and 3.9.9 (the scrapy shell).  I need to install PyTorch, but PyTorch isn't working with Python 3.10 right now... And when I was tring to build pytorch from source with M1, pytorch dragged me back to install conda before compiling ,which only supports upto python 3.9.7 right now. It's like a dead loop...

**Comment by shaders** [comment]
Same thing happening on Python 3.8.9

**Comment by upuil** [comment]
`pip3 uninstall pyopenssl` may get around to this.

**Comment by anribras** [comment]
Resolved under newest python 3.10.0 , using conda virturl env 
conda create -n py310 python=3.10
my laptop is Mac m1 .

**Comment by candlerb** [comment]
@shaders:
> Same thing happening on Python 3.8.9

Can you give a *specific* way to reproduce the problem?  e.g. a short, standalone python script which reproduces it for you?

**Comment by shaders** [comment]
@candlerb I've updated requests module from 2.21 to 2.26 and the problem was gone (probably because requests module no longer uses pyssl: https://docs.python-requests.org/en/latest/community/updates/

> 2.26.0 (2021-07-13)
> The requests[security] extra has been converted to a no-op install. PyOpenSSL is no longer the recommended secure option for Requests. (#5867)

```
-requests==2.21.0
+requests==2.26.0
```

**Comment by millnerryan** [comment]
Figured it out following @anribras 's advice. M1 mac, had the same issue here. As @anribras says, I upgraded Python in my conda env to 3.10.2 and now this issue is resolved.

**Comment by peirisi** [comment]
I'm using python 3.10.2 but i can't open scrapy
![image](https://user-images.githubusercontent.com/47599755/154276025-7ecb97b9-a435-493e-aa51-da8c96632a5a.png)
m1mac monterey12.2.1 (21D62)

**Comment by tengwang0318** [comment]
> I have tested the latest verion of pyopenssl with Python 3.10.0 and 3.9.9 on M1 MacBook Pro, it turns out (probably) a problem of the Python Interpreter on M1. The Python interpreter 3.10 (might) change the ways to access(write) memory on M1 chips.

I also meet that question!

**Comment by lcy19991113** [comment]
> > I have tested the latest verion of pyopenssl with Python 3.10.0 and 3.9.9 on M1 MacBook Pro, it turns out (probably) a problem of the Python Interpreter on M1. The Python interpreter 3.10 (might) change the ways to access(write) memory on M1 chips.
> 
> I also meet that question! @[Alexander Liu](https://github.com/xros) I think you can use mini-conda to install torch where python version is 3.8, and use python which version is 3.10 to install scrapy.

thanks！！！

**Comment by risicle** [comment]
We see this still in the test suites of several packages in Nix on darwin-aarch64 and the thing all affected packages has in common is *async*. 

> And not for nothing, but our test suite runs without segfaulting on an M1, so either our coverage is lousy (quite possible!) or there's slightly more involved in reproducing this than just using an M1.

I note your test suite doesn't have any asyncio examples.

**Comment by reaperhulk** [comment]
If there's a reliable reduced test case that reproduces this that's the next step in determining how to fix/work around the issue.

**Comment by WittmannF** [comment]
@reaperhulk , I am getting the above error when making a connection on snowflake. Sharing in case it is helpful for reproducibility:
```
# pip install snowflake-connector-python
import snowflake.connector
conn = snowflake.connector.connect(...)
```

[Here's](https://pastebin.pl/view/1a66aaab) the full traceback

**Comment by reaperhulk** [comment]
Unfortunately the issue here is that these errors don't reproduce with arbitrary Python on M1. I just tested that on my M1 Max running 3.10 from pyenv and had no error.

**Comment by ipointer-netrise** [comment]
I didn't have this error before installing these packages, and I do now:

```
7093  pip3 install numpy
7094  pip3 install dataclasses-json
7095  pip3 install scipy
7108  pip3 install solidpython
```

I also installed conda:

```
7100  curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"\nbash Mambaforge-$(uname)-$(uname -m).sh
7101  -
7102  conda install -c conda-forge -c cadquery cadquery=2
```

Uninstalling the packages above did not resolve the issue, but removing `~/mambaforge` resolved the issue.

**Comment by Amar1729** [comment]
I have a reproducible example, but I don't fully understand why it's happening.

First of all, I do **NOT** see the `ffi.callback()` error at all with `pyenv`'s python versions, and I also do **NOT** see the error while using a virtual environment. I only see the error when using a formula's internal homebrew version of python that uses the homebrew `libffi` library.

Code sample - `get_context_factory` definition mostly taken from deluge's [`crypto_utils`](https://github.com/deluge-torrent/deluge/blob/deluge-2.0.5/deluge/crypto_utils.py#L50), and the other functions are cherry-picked from some `twisted` wrapper code (in particular the [`internet._sslverify._makeContext`](https://github.com/twisted/twisted/blob/twisted-22.1.0/src/twisted/internet/_sslverify.py#L1635) function):

```python
#! /usr/bin/env python3

from OpenSSL import SSL


class OpenSSLCertificateOptions:
    _contextFactory = SSL.Context
    _context = None

    def __init__(self):
        self._options = (
            SSL.OP_NO_SSLv2 | SSL.OP_NO_COMPRESSION | SSL.OP_CIPHER_SERVER_PREFERENCE
        )

        self._mode = SSL.MODE_RELEASE_BUFFERS

        self.method = SSL.SSLv23_METHOD

    def getContext(self):
        if self._context is None:
            self._context = self._makeContext()
        return self._context

    def _makeContext(self):
        ctx = self._contextFactory(self.method)
        ctx.set_options(self._options)
        ctx.set_mode(self._mode)

        verifyFlags = SSL.VERIFY_NONE

        # It'd be nice if pyOpenSSL let us pass None here for this behavior (as
        # the underlying OpenSSL API call allows NULL to be passed).  It
        # doesn't, so we'll supply a function which does the same thing.
        def _verifyCallback(conn, cert, errno, depth, preverify_ok):
            return preverify_ok

        ctx.set_verify(verifyFlags, _verifyCallback)


def get_context_factory():
    cert_options = OpenSSLCertificateOptions()

    # this call is borked - ffi.callback
    # import pdb; pdb.set_trace()
    ctx = cert_options.getContext()

    return cert_options


if __name__ == "__main__":
    get_context_factory()
    print("sample worked!")
```

Now, to actually see the error you have to jump through some hoops. I saw this error with the version of python that gets installed via my `deluge-meta` Homebrew formula (deluge depends on `libffi`, so that formula is a dependency here). A homebrew formula that uses Python creates a virtual environment under its location to use (conventionally named `libexec`) and installs any resources (e.g. python wheels). So, I have a directory like this under my Homebrew prefix:

```
$ cd /opt/homebrew/opt/deluge-meta
$ ls -Fl1
AUTHORS
bin/
CHANGELOG.md
INSTALL_RECEIPT.json
libexec/
LICENSE
README.md
share/
```

I can reproduce the error using the sample above with this formula's python (which depends on `libffi` and has `pyopenssl` installed):

```
$ /opt/homebrew/opt/deluge-meta/libexec/bin/python sample.py

Traceback (most recent call last):
  File "/private/tmp/deluge/minimal_2.py", line 51, in <module>
    get_context_factory()
  File "/private/tmp/deluge/minimal_2.py", line 45, in get_context_factory
    ctx = cert_options.getContext()
  File "/private/tmp/deluge/minimal_2.py", line 21, in getContext
    self._context = self._makeContext()
  File "/private/tmp/deluge/minimal_2.py", line 37, in _makeContext
    ctx.set_verify(verifyFlags, _verifyCallback)
  File "/opt/homebrew/Cellar/deluge-meta/2.0.5/libexec/lib/python3.10/site-packages/OpenSSL/SSL.py", line 1128, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/opt/homebrew/Cellar/deluge-meta/2.0.5/libexec/lib/python3.10/site-packages/OpenSSL/SSL.py", line 359, in __init__
    self.callback = _ffi.callback(
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

However, I do not see the error with homebrew's python:

```
$ /opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install pyopenssl
$ /opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/bin/python3.9 sample.py
sample worked!
```

Or with virtual environments created with homebrew's or pyenv's python
```
# homebrew python 3.9
$ /opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m venv venv

# homebrew python 3.10
$ /opt/homebrew/Cellar/python@3.10/3.10.4/bin/python3 -m venv venv

# python 3.9 (pyenv)
$ /Users/amar1729/.pyenv/shims/python3 -m venv venv

# system python 3.8 does not work - pip installing cryptography fails due to missing openssl header
```

Using venvs created with any of these pythons (and pip installing `pyopenssl`) results in a working sample:
```
# install deps and run:
$ venv/bin/pip install pyopenssl
$ venv/bin/python sample.py
sample worked!
```

If you would like to reproduce this without installing my tap (understandable) I've created a simple formula definition which you can use:

```bash
# you never have to push this tap upstream, `brew` will use the local file just fine
$ brew tap-new arbitrary-username/openssl-env
$ brew edit arbitrary-username/openssl-env/openssl-env.rb  # paste the content of the next code block
$ brew install openssl-env

$ /opt/homebrew/opt/openssl-env/libexec/bin/python sample.py
<should fail>
```

`openssl-env.rb`
```ruby
class OpensslEnv < Formula
  include Language::Python::Virtualenv

  desc "Meta package for pyopenssl testing"
  homepage "https://github.com/pyca/pyopenssl"
  url "https://github.com/pyca/pyopenssl/archive/refs/tags/22.0.0.tar.gz"
  sha256 "4e92f6c2f08a8d1f0d9695335037a3d50ef8f58cd326514b89104acb9abb2838"

  depends_on "rust" => :build
  depends_on "libffi"
  depends_on "python@3.9"

  resource "cffi" do
    url "https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz"
    sha256 "920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954"
  end

  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/51/05/bb2b681f6a77276fc423d04187c39dafdb65b799c8d87b62ca82659f9ead/cryptography-37.0.2.tar.gz"
    sha256 "f224ad253cc9cea7568f49077007d2263efa57396a2f2f78114066fd54b5c68e"
  end

  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/5e/0b/95d387f5f4433cb0f53ff7ad859bd2c6051051cebbb564f139a999ab46de/pycparser-2.21.tar.gz"
    sha256 "e644fdec12f7872f86c58ff790da456218b10f863970249516d60a5eaca77206"
  end

  resource "pyOpenSSL" do
    url "https://files.pythonhosted.org/packages/35/d3/d6a9610f19d943e198df502ae660c6b5acf84cc3bc421a2aa3c0fb6b21d1/pyOpenSSL-22.0.0.tar.gz"
    sha256 "660b1b1425aac4a1bea1d94168a85d99f0b3144c869dd4390d27629d0087f1bf"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    system "true"
  end
end
```

Note the line `depends_on "libffi"`. I've found it is that line in particular that causes this failure from a formula's python. If you remove it (or change it to `uses_from_macos "libffi"`, which uses the **system** version of libffi), I see that `sample.py` running perfectly fine. While `uses_from_macos` is an acceptable solution for formulae that depend directly on `libffi`, it is infeasible for formulae that recursively depend on it and use the homebrew version (e.g. my deluge formula, which depends on several deps that depend on `cairo > glib > libffi`).

----

I've tried various invocations of `codesign`, as suggested by the cffi docs and documented in my repo's issue, but even signing the `python` symlinks or homebrew `libffi/lib/libffi.dylib` with the appropriate entitlements doesn't make MacOS let a formula-bundled python run an insecure script.

**Comment by reckenrode** [comment]
I don’t think it’s codesigning that lets it work. I did a diff of Apple’s libffi from their [OSS release][1] and [upstream][2]. There appear to be changes that they’re still working on upstreaming. For example: https://github.com/libffi/libffi/pull/621.

I’m building nixpkgs’s libffi with this patch to see if that allows PyOpenSSL to work on aarch64-darwin. Unfortunately, I will be away for most of the day and won’t be able to check the results before this evening EDT.

[1]: https://github.com/apple-oss-distributions/libffi
[2]: https://github.com/libffi/libffi

**Comment by reckenrode** [comment]
Following up from yesterday: unfortunately, no luck. I was able to manually build `libffi-trampolines.dylib`, but the PyOpenSSL tests are still failing.

**Comment by tjni** [comment]
Would someone with more experience and insight into this project be willing to comment on the following proposal? I would be willing to work on it, but I want to sanity check it.

I'm only going to focus on uses of the old-style CFFI `ffi.callback` function in `SSL.py` for now. In these usages, the callback functions have two properties:

1. They receive an argument that can be used to resolve to an OpenSSL `SSL` struct.
2. They are saved as instance members of either `Connection` or `Context`.

For each usage of `ffi.callback`, could we therefore write a generic version that is built and made available through the new CFFI `extern Python` approach, which does the following:

```
@ffi.def_extern()
def my_generic_callback(ssl, ...):
  # Look up Connection from ssl
  # If necessary, look up Context from Connection
  # Find the actual callback saved on the Connection or Context instance
  # Call it
```

**Comment by tiran** [comment]
Last time I checked ``@ffi.def_extern()`` was using a single, static C global to store a pointer to the callback function. The approach is incompatible with multiple subinterpreters. If that's still the case then you need a much more complicated implementation.

**Comment by aljosa** [comment]
Is there a bounty program for this?
I want this fixed for macos (apple m1 chip), or more specifically, removed from other packages depending on pyopenssl.

End goal is to normally use python ecosystem w/ nix.

Any of these options seem reasonable or is this something that will last for a few years (like python3 transition)?

**Comment by jpzhangvincent** [comment]
> `pip3 uninstall pyopenssl` may get around to this.

But when I try to import "snowflow.connector", I got "ModuleNotFoundError: No module named 'OpenSSL'
"

**Comment by bergkvist** [comment]
I think what @tjni is suggesting might be the easiest (and maybe only) way of getting this to work.

As @tiran points out, `@ffi.def_extern()` doesn't allow for dynamically creating new callbacks which the current implementation of pyopenssl requires.

You'd need to have a constant number of statically defined callback functions on the C-side which handles all callbacks, and somehow routes these callbacks back to their respective contexts on the Python-side. This routing would probably need some kind of global lookup table on the Python-side for each usage of ffi.callback.

**Comment by bazilione** [comment]
Snowflake requires Python 3.8 (as of 09/30/2022) and Python 3.10 doesn't fix it for Snowflake issue.

The fix for Snowflake is here:
https://docs.snowflake.com/en/developer-guide/snowpark/python/setup.html#prerequisites

Reposting here:
#
CONDA_SUBDIR=osx-64 conda create -n snowpark python=3.8 numpy pandas -c https://repo.anaconda.com/pkgs/snowflake
conda activate snowpark
conda config --env --set subdir osx-64
#

**Comment by brentonmallen1** [comment]
I wanted to point out an edge case that I'm running into.  The proposed work around (changing to `osx-64`) doesn't seem to play well when attempting to pair a snowflake connection with tensorflow on an M1.  The tensorflow installation (via miniforge) requires an `osx-arm64` architecture.  This workaround forces an `osx-64` (x86) architecture which means the `tensorflow-deps` won't be found using the miniforge `apple` channel.

**Comment by yogeshbhate** [comment]
> conda create -n py310 python=3.10

yes this resolves my issue too with my M1 chip macbook pro.

**Comment by brentonmallen1** [comment]
I'm glad upgrading to 3.10 seems to work and I'll definitely do that when I'm able, but unfortunately, upgrading isn't an option at the moment.

**Comment by Maaverick** [comment]
Still have this error on:

macOS (2021) Monterey version 12.4
Apple M1 Pro
---
conda env
scrapy=2.7.1
pyopenssl=22.1.0
python=3.10.6

**Comment by jonbuffington** [comment]
@Maaverick I too still experience the issue using conda-forge to install the same versions you listed.

**Comment by tgy** [comment]
I have this issue too on a M1, with `Python 3.10.6`

**Comment by sfc-gh-mkeller** [comment]
The root cause of this issue has been found and fixed by [conda-forge/cffi-feedstock#47 (files)](https://github.com/conda-forge/cffi-feedstock/pull/47/files) for Conda users (a simple `conda install cffi` should update you to build number 3 of version `1.15.1` has the fix included).
The solution itself is described at [foss.heptapod.net/pypy/cffi/-/blob/branch/default/c/_cffi_backend.c#L64-89](https://foss.heptapod.net/pypy/cffi/-/blob/branch/default/c/_cffi_backend.c#L64-89). This macro just needs to be enabled for `cffi` to build correctly. This macro needs to be enabled for M1 macs

**Comment by jonbuffington** [comment]
@sfc-gh-mkeller Thanks for the pointer! It appears the changes have not been merged yet though. Hopefully, the change will be merged and build 3 will be available in the condo-forge channel soon.

**Comment by WittmannF** [comment]
Still getting the issue in my Mac Pro 2021 M1 running MacOS Monterey. Tried all suggestions from above:
- Using Python 3.10
- Install cffi 1.15.1
- Updating requests

Still not working. Here's my full enviroment:
```
❯ conda list
# packages in environment at /Users/wittmann/miniforge3/envs/fixssl:
#
# Name                    Version                   Build  Channel
_ipython_minor_entry_point 8.7.0                hb6b4a82_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1          py310h2399d43_2    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
cryptography              38.0.4                   pypi_0    pypi
debugpy                   1.6.4           py310h0f1eb42_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.13                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
idna                      3.4                      pypi_0    pypi
ipykernel                 6.19.2             pyh736e0ef_0    conda-forge
ipython                   8.7.0              pyhd1c38e8_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.8              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.0           py310hbe9552e_0    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
openssl                   3.0.7                h03a7124_1    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.4           py310h8e9501a_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pynubank                  2.21.1                   pypi_0    pypi
pyopenssl                 22.1.0                   pypi_0    pypi
python                    3.10.8          h3ba56d0_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.21.0             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pyzmq                     24.0.1          py310hc407298_1    conda-forge
qrcode                    7.3.1                    pypi_0    pypi
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-pkcs12           1.14                     pypi_0    pypi
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tornado                   6.2             py310h8e9501a_1    conda-forge
traitlets                 5.7.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.13                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
```

Anything else I should try? The package I'm trying to use is called [pynubank](https://github.com/andreroggeri/pynubank). Here's the full traceback:

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[10], line 1
----> 1 nu.authenticate_with_cert(
      2     os.getenv("CPF"), 
      3     os.getenv("NU_PASS"),
      4     'cert.p12'
      5 )

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/pynubank/nubank.py:118, in Nubank.authenticate_with_cert(self, cpf, password, cert_path)
    109 url = self._discovery.get_app_url('token')
    110 payload = {
    111     'grant_type': 'password',
    112     'client_id': 'legacy_client_id',
   (...)
    115     'password': password
    116 }
--> 118 response = self._client.post(url, json=payload)
    120 self._save_auth_data(response)
    121 self._auth_mode = AuthMode.APP

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/pynubank/utils/http.py:46, in HttpClient.post(self, url, json)
     45 def post(self, url: str, json: dict) -> dict:
---> 46     return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/requests_pkcs12.py:157, in post(*args, **kwargs)
    156 def post(*args, **kwargs):
--> 157     return request('post', *args, **kwargs)

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/requests_pkcs12.py:136, in request(*args, **kwargs)
    129 pkcs12_adapter = Pkcs12Adapter(
    130     pkcs12_data=pkcs12_data,
    131     pkcs12_filename=pkcs12_filename,
    132     pkcs12_password=pkcs12_password,
    133     ssl_protocol=ssl_protocol,
    134 )
    135 session.mount('https://', pkcs12_adapter)
--> 136 return session.request(*args, **kwargs)

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/requests/sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/requests/sessions.py:701, in Session.send(self, request, **kwargs)
    698 start = preferred_clock()
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)
    704 elapsed = preferred_clock() - start

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/requests/adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    487 try:
    488     if not chunked:
--> 489         resp = conn.urlopen(
    490             method=request.method,
    491             url=url,
    492             body=request.body,
    493             headers=request.headers,
    494             redirect=False,
    495             assert_same_host=False,
    496             preload_content=False,
    497             decode_content=False,
    498             retries=self.max_retries,
    499             timeout=timeout,
    500         )
    502     # Send the request.
    503     else:
    504         if hasattr(conn, "proxy_pool"):

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    700     self._prepare_proxy(conn)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.
    717 response_conn = conn if not release_conn else None

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/urllib3/connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    384 # Trigger any extra validation we need to do.
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.
    389     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/urllib3/connectionpool.py:1042, in HTTPSConnectionPool._validate_conn(self, conn)
   1040 # Force connect early to allow us to validate the connection.
   1041 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1042     conn.connect()
   1044 if not conn.is_verified:
   1045     warnings.warn(
   1046         (
   1047             "Unverified HTTPS request is being made to host '%s'. "
   (...)
   1052         InsecureRequestWarning,
   1053     )

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/urllib3/connection.py:401, in HTTPSConnection.connect(self)
    395     self.ssl_context = create_urllib3_context(
    396         ssl_version=resolve_ssl_version(self.ssl_version),
    397         cert_reqs=resolve_cert_reqs(self.cert_reqs),
    398     )
    400 context = self.ssl_context
--> 401 context.verify_mode = resolve_cert_reqs(self.cert_reqs)
    403 # Try to load OS default certs if none are given.
    404 # Works well on Windows (requires Python3.4+)
    405 if (
    406     not self.ca_certs
    407     and not self.ca_cert_dir
   (...)
    410     and hasattr(context, "load_default_certs")
    411 ):

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py:451, in PyOpenSSLContext.verify_mode(self, value)
    449 @verify_mode.setter
    450 def verify_mode(self, value):
--> 451     self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/OpenSSL/SSL.py:1135, in Context.set_verify(self, mode, callback)
   1132 if not callable(callback):
   1133     raise TypeError("callback must be callable")
-> 1135 self._verify_helper = _VerifyHelper(callback)
   1136 self._verify_callback = self._verify_helper.callback
   1137 _lib.SSL_CTX_set_verify(self._context, mode, self._verify_callback)

File ~/miniforge3/envs/autofinance/lib/python3.10/site-packages/OpenSSL/SSL.py:365, in _VerifyHelper.__init__(self, callback)
    362         else:
    363             return 0
--> 365 self.callback = _ffi.callback(
    366     "int (*)(int, X509_STORE_CTX *)", wrapper
    367 )

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

```

**Comment by jonbuffington** [comment]
@WittmannF You are running build 2 of cffi (py310h2399d43_2) and that does not contain the patch @sfc-gh-mkeller shared. The patch is not yet merged and a new build published yet,.

**Comment by WittmannF** [comment]
Thanks @jonbuffington ! I was able to solve it here with `pip install cffi`

**Comment by Gastastrophe** [comment]
> @WittmannF Yep. Until build 3 of `cffi` is available, I have been activating the conda/mamba env and:
> 
> ```shell
> (my_env) $ pip install --force-reinstall 'cffi>=1.15.1'
> ```

Confirming that this worked for me on a failing conda environment with only snowflake connector, pandas, and jupyter installed.

**Comment by jonbuffington** [comment]
The patch @sfc-gh-mkeller found is merged and build 3 is available in the condo-forge channel. The above workaround I mentioned above is no longer necessary.

**Comment by 1eliton** [comment]
> @WittmannF Yep. Until build 3 of `cffi` is available, I have been activating the conda/mamba env and:
> 
> ```shell
> (my_env) $ pip install --force-reinstall 'cffi>=1.15.1'
> ```

It worked here. thanks a lot!

**Comment by includeno** [comment]
> @WittmannF Yep. Until build 3 of `cffi` is available, I have been activating the conda/mamba env and:
> 
> ```shell
> (my_env) $ pip install --force-reinstall 'cffi>=1.15.1'
> ```
This is useful! It works on python 3.9.Thank you a lot!

**Comment by ftmoztl** [comment]
> > @WittmannF Yep. Until build 3 of `cffi` is available, I have been activating the conda/mamba env and:
> > ```shell
> > (my_env) $ pip install --force-reinstall 'cffi>=1.15.1'
> > ```
> 
> It worked here. thanks a lot!

As an M1 user, it worked for me also without using conda virtual env. Thank you so much!
